### ISSUE TITLE
Trying to get USB connection to work

### ISSUE THREAD

**Issue by Tab-Triggerhappy** [mechano/Kingroon_KP3S_Marlin_Firmware#2]
I wanted to build the firmware myself to add swedish and also I can't get Windows to connect via USB.
Do I need to build the "...USBMOD" or is that something else?

I get 3 options to build and built the first. The other options are MAPLE and USBMOD, but I don't know what the differences are.
Both your build and my build works in my printer, but not the USB connection.
Any suggestions are welcome, thanks in advance :)

**Comment by mechano** [comment]
When you say USB connection are you talking about using Pronterface to give gcode commands, or print via Octoprint?

Because it works. But at 250000 baud it has lot of errors so the tty needs to be set at 115200, but at this speed printing is a bit slow.

**Comment by Tab-Triggerhappy** [comment]
Print with Octoprint or monitor in Cura.
I have tested all my cables including a short double shielded.
Perhaps the printer's port is broken. Starting to think that.

Edit:
I built the usbmod version, but no change. Removed webcam, tried different ports.
Search for updates and ran diagnose. I think you can close this.
The SD card method is more reliable anyway :)
